apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: post-service
          image: slopeoasisacr.azurecr.io/post-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
              - name: SPRING_DATASOURCE_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: posts-db-secret
                    key: PGUSER
              - name: SPRING_DATASOURCE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: posts-db-secret
                    key: PGPASSWORD
              - name: PGHOST
                valueFrom:
                  secretKeyRef:
                    name: posts-db-secret
                    key: PGHOST
              - name: PGPORT
                valueFrom:
                  secretKeyRef:
                    name: posts-db-secret
                    key: PGPORT
              - name: PGDATABASE
                valueFrom:
                  secretKeyRef:
                    name: posts-db-secret
                    key: PGDATABASE
              - name: AZURE_CONTAINER_NAME
                valueFrom:
                  configMapKeyRef:
                    name: post-service-config
                    key: AZURE_CONTAINER_NAME
              - name: AZURE_CONNECTION_STRING
                valueFrom:
                  secretKeyRef:
                    name: post-blob-secret
                    key: AZURE_CONNECTION_STRING
              - name: USER_API_URL
                value: http://user-service:8080

          envFrom:
            - configMapRef:
                name: post-service-config
