apiVersion: v1
kind: Secret
metadata:
  name: post-blob-secret
type: Opaque
data:
  AZURE_CONNECTION_STRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXNsb3Blb2FzaXNibG9iO0FjY291bnRLZXk9VUY1c3JUb0l5ZVRnNlk3TS9BTXNVVHFJZ2NHWk52dGNNeHlvdXdqS1BSRUwvY1h4TUtMS1dLUFJveDkwSVROQ09XeW5UOStiTU00TCtBU3RuYWZpd3c9PTtFbmRwb2ludFN1ZmZpeD1jb3JlLndpbmRvd3MubmV0Cg==
