apiVersion: v1
kind: Secret
metadata:
  name: posts-db-secret
type: Opaque
data:
  PGHOST: dXNlcmRhdGFiYXNlLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  PGUSER: dXNlcmFkbWlu
  PGPORT: NTQzMg==
  PGDATABASE: cG9zdHNkYg==
  PGPASSWORD: cGFzc3dvcmQyOTch